"""Add Session model

Revision ID: 39614695ac00
Revises: 76e677b9e864
Create Date: 2024-08-16 02:34:51.503505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39614695ac00'
down_revision = '76e677b9e864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('notes')
        batch_op.drop_column('therapist')
        batch_op.drop_column('sessions_completed')
        batch_op.drop_column('appointment_date')
        batch_op.drop_column('procedure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('appointment_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sessions_completed', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('therapist', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('session')
    # ### end Alembic commands ###
